# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_countdown_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
