# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_auto_20170320_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='email',
            field=models.CharField(default='blank@blank.com', max_length=100),
            preserve_default=False,
        ),
    ]
