# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0005_countdown_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
