# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0006_countdown_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
